### ISSUE TITLE
> php artisan clear-compiled: [PDOException] could not find driver  

### ISSUE THREAD

**Issue by francesco1119** [taviroquai/mapigniter2#16]
This is the error after running "php composer.phar install --prefer-dist":
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files

> php artisan clear-compiled

  [PDOException]  
  could not find driver  

Script php artisan clear-compiled handling the post-install-cmd event returned with an error

  [RuntimeException]  
  Error Output:

**Comment by taviroquai** [comment]
Hello,

By default mapigniter2 uses a PostgreSQL database. If you did not change this. I suspect the Laravel error is asking for a package that may be missing: PHP PostgreSQL extension.

If you are on a debian-based distro try install with: sudo apt-get install php-pgsql
Then, restart your web-server. (for apache, sudo service apache restart
Then run again: php composer.phar install --prefer-dist

Cheers

**Comment by francesco1119** [comment]
Thank you, I saw was written:

"[...]defaults to PostgreSQL server and has currently only been tested on PostgreSQL, but should work with MySQL, [...]"

So now we can say that it cannot work with MySQL, right?
Or is there any workaround?

**Comment by taviroquai** [comment]
@francesco1119 mapigniter2 is based on Laravel and it works with MySQL.

Hold on, I testing now with mysql :)

**Comment by taviroquai** [comment]
Well,

Some database columns defined in Laravel migrations as being "boolean", are being return as not boolean data types.

As workaround, we had to specify casts to models attributes. For example, look at model Layeritem.

More bug my arise from MySQL and PostgreSQL differences.

For now, run again (this will correct foreigh key adequate for MySQL):
php artisan migrate:reset
php artisan migrate
php artisan db:seed

And follow the rest of install instructions. Report any bugs and thanks!!!

**Comment by taviroquai** [comment]
Oh, don't forget to set your database settings in file .env ;)

**Comment by francesco1119** [comment]
.env => done!
mysite/public => 404 Page Not Found 

Strange, this time there were no errors during installation

**Comment by taviroquai** [comment]
@francesco1119 look at Apache logs. Also, Laravel uses .htaccess so be sure to enable rewite module in apache with:

sudo a2enmod rewrite
sudo service apache2 restart

I suppose with gave the write permissions to the folders indicated by install...

**Comment by francesco1119** [comment]
Everything works!
Thank you!
