### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by victorricardo** [taviroquai/mapigniter2#18]
Could create the folder mapigniter2/resources/lang/es to raise the Spanish translation ?.

**Comment by taviroquai** [comment]
Hola Ricardo,

Yo voy ententar hablar un poco en espanol :)

No tenia entiendido lo que pretendias. Ahora lo vi tu branches e tenias que hacer um pedido "Pull Request".

Perdon. Puedes ententar recolocar tus traduciones despues de merge master e hacer lo pedido "Pull Request"? Gracias.

**Comment by taviroquai** [comment]
Muchas gracias Ricardo! :)
