### ISSUE TITLE
artisan db:seed hangs in windows

### ISSUE THREAD

**Issue by robe2** [taviroquai/mapigniter2#30]
I think this happened to me last time to so might be just a windows issue.

When I run:

```
artisan db:seed

```

It just seems to sit there for a while, so I just Ctrl-X Ctrl-C out of it.

Everything at a glance seems okay after that, but not sure what that step is supposed to do and how long it should take.

I see all the tables created in postgres db.

**Comment by taviroquai** [comment]
Hi Regina,

That command will seed the database using the file **database/seeds/DatabaseSeed.php**

It should fill the database with preinstall data defined in that file.
It also copies a preinstall storage data folder.

There is a copy command in line 29 for windows... maybe is that the problem.

**Comment by robe2** [comment]
Does seem to be the xcopy, but what's weird is if I end task and then rerun it it works fine.

So it seems like maybe it's prompting for something as part of the create folder process because the storage folder doesn't exist first time around.

Anyway I'll revisit again by just running explicitly the xcopy to see if it prompts for something if the folder doesn't exist.

**Comment by taviroquai** [comment]
Thanks Regina.

I did a commit where I changed the order of the xcopy arguments. Now it is:
shell_exec('xcopy ' . public_path('storage.dist') . ' ' . public_path('storage') . ' /H /E /Y');

Please try now with the master branch.

**Comment by taviroquai** [comment]
I got it working. Please robe verify with master branch.
