### ISSUE TITLE
Instructions enhancements suggestions (mostly issues for users of windows)

### ISSUE THREAD

**Issue by robe2** [taviroquai/mapigniter2#5]
Marco,
Would probably be good to state the minimum requirements of your app for each version.

Just starting up:

1) Looks like you require PHP 5.3.3+ (or maybe it's because I updated the composer cause it said it's 60 days old.  Most people will have that, I just started testing with an old beatup PHP to check minimums.

2) On windows ../composer does not work, not sure if other OS will have issue.  On Linux works fine since Linux reads the header to determine what executable to run.

Might want to specify  that on some OS

You might have to do

path/to/php  composer 

might need to do that if for whatever reason you have multiple versions of PHP.

After I finish installing I'll see if I can provide a patch to instructions at least.  Those are just 2 things I noticed starting off.  I'm probably also rare cause my clients are heavy Windows users so more focused on MS windows issues. So I will run into issues most others may not.

**Comment by taviroquai** [comment]
Awesome and thanks robe!

Sure Windows install instructions/script is a must.

**Comment by taviroquai** [comment]
@robe2 

About your points
1) Laravel 5.1 required PHP 5.5.9

2) On windows one have to run: php composer.phar install --prefer-dist
Sure that php must be on include path, or put the full path.

Cheers
