### ISSUE TITLE
How to run on non-standard database port?

### ISSUE THREAD

**Issue by robe2** [taviroquai/mapigniter2#6]
This might be a question rather than an issue.  In the .env file, there is no provision to specify the database port and I rarely run my postgres server on 5432.  Does that get put as part of the DB_HOST? or something else.  Anyrate should be noted in instructions if it should be part of DB_HOST.

I haven't used codeigniter in while so maybe there is a standard for it I'm not familiar with.

**Comment by robe2** [comment]
answered my own question, still should be added to the instructions though.

To run on non-standard port, you change the .env DB_HOST line to 

```

DB_HOST=localhost port=5439

```

where 5439 is the database port, though I guess you could just always put that in the env so it's obvious to people.

**Comment by taviroquai** [comment]
Laravel allows you to specify the port with DB_PORT as it will be used on config/database.php as env('DB_PORT', 5432)

**Comment by taviroquai** [comment]
@robe2 please fix README.md about this. It should be on .env file like this:

```
DB_HOST=localhost
DB_PORT=9999
```

And then in inform to use this environment variable in config/database.php like this:

```
'pgsql' => [
            'driver'   => 'pgsql',
            'host'     => env('DB_HOST', 'localhost'),
            'port'     => env('DB_PORT', 5432),
```

**Comment by taviroquai** [comment]
Ok I have corrected it already.

**Comment by robe2** [comment]
Okay let's close this one.

**Comment by robe2** [comment]
@taviroquai I'm reopening this because I noticed you didn't change the config/database.php.  Wouldn't it be easier to just change it and then you can get rid of the second set of instructions about patching config/database.php?

**Comment by robe2** [comment]
Also thinking if we add DB_PORT to the .env.sample and set it to 5432, we don't need any instructions since it would be obvious to users what to change by lookng at the .env.sample.

**Comment by taviroquai** [comment]
@robe2 Well I think at that configuration level, developrs know what to do. But you are right, giving them the configuration port on .env.example will make their lifes easier.

So, go for it :)
