### ISSUE TITLE
Special instructions for windows users running on IIS

### ISSUE THREAD

**Issue by robe2** [taviroquai/mapigniter2#7]
I got this running on Windows 2012 under IIS without too much fuss.  I ran into some stumbling blocks which may not be obvious for certain users.  I think for running on Apache on windows your instructions are probably good enough.

If you are okay with it, I can write up a patch (as a separate .md file), for users trying to deploy on windows IIS.  Which would be a lot of people stuck in corporate that are only allowed windows stuff.

**Comment by taviroquai** [comment]
Sure. Very nice ;)
